In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.cluster import KMeans 
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_samples, silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.cluster.hierarchy import fcluster
from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [4]:
df = pd.read_csv("leaf_data_uci_updated.csv")
df

Eccentricity  Aspect Ratio  Elongation  Solidity  Stochastic Convexity  \
0         0.72694        1.4742     0.32396  0.985350              1.000000   
1         0.74173        1.5257     0.36116  0.981520              0.998250   
2         0.76722        1.5725     0.38998  0.977550              1.000000   
3         0.73797        1.4597     0.35376  0.975660              1.000000   
4         0.82301        1.7707     0.44462  0.976980              1.000000   
..            ...           ...         ...       ...                   ...   
335       0.37522        1.1417     0.81725  0.761323              0.915575   
336       0.28064        1.0849     0.75319  0.761323              0.915575   
337       0.35344        1.0329     0.78147  0.761323              0.915575   
338       0.59988        1.1427     0.71532  0.761323              0.915575   
339       0.47195        1.0901     0.85409  0.761323              0.915575   

     Isoperimetric Factor  Maximal Indentation Depth  Lobedness  \
0                0.835920                   0.004657   0.003947   
1                0.798670                   0.005242   0.005002   
2                0.808120                   0.007457   0.010121   
3                0.816970                   0.006877   0.008607   
4                0.754930                   0.007428   0.010042   
..                    ...                        ...        ...   
335              0.125230                   0.091860   1.016331   
336              0.136860                   0.078996   1.016331   
337              0.135030                   0.089763   1.016331   
338              0.157470                   0.105303   1.016331   
339              0.078376                   0.105303   1.016331   

     Average Intensity   Average Contrast  Smoothness   Third moment  \
0             0.047790           0.127950    0.016108       0.005232   
1             0.024160           0.090476    0.008119       0.002708   
2             0.011897           0.057445    0.003289       0.000921   
3             0.015950           0.065491    0.004271       0.001154   
4             0.007938           0.045339    0.002051       0.000560   
..                 ...                ...         ...            ...   
335           0.114880           0.208610    0.041703       0.013344   
336           0.141220           0.218300    0.045488       0.012002   
337           0.097663           0.207030    0.041101       0.016123   
338           0.050389           0.135850    0.018121       0.006190   
339           0.082007           0.187820    0.034074       0.013487   

     Uniformity  Entropy  
0      0.000275  1.17560  
1      0.000075  0.69659  
2      0.000038  0.44348  
3      0.000066  0.58785  
4      0.000023  0.34214  
..          ...      ...  
335    0.000820  2.02810  
336    0.001137  2.40590  
337    0.000453  1.69350  
338    0.000265  1.15260  
339    0.000329  1.56230  

[340 rows x 14 columns]

In [7]:
df.duplicated().sum()

0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Eccentricity               340 non-null    float64
 1   Aspect Ratio               340 non-null    float64
 2   Elongation                 340 non-null    float64
 3   Solidity                   340 non-null    float64
 4   Stochastic Convexity       340 non-null    float64
 5   Isoperimetric Factor       340 non-null    float64
 6   Maximal Indentation Depth  340 non-null    float64
 7   Lobedness                  340 non-null    float64
 8   Average Intensity          340 non-null    float64
 9    Average Contrast          340 non-null    float64
 10  Smoothness                 340 non-null    float64
 11   Third moment              340 non-null    float64
 12  Uniformity                 340 non-null    float64
 13  Entropy                    340 non-null    float64

In [9]:
df.describe()

Eccentricity  Aspect Ratio  Elongation    Solidity  \
count    340.000000    340.000000  340.000000  340.000000   
mean       0.719854      1.902051    0.513760    0.919101   
std        0.208311      0.888783    0.195583    0.075247   
min        0.117080      1.006600    0.107610    0.761323   
25%        0.550622      1.211300    0.349623    0.890667   
50%        0.763450      1.570750    0.501855    0.948130   
75%        0.895097      2.343100    0.633373    0.976897   
max        0.998710      4.040800    0.948340    0.993880   

       Stochastic Convexity  Isoperimetric Factor  Maximal Indentation Depth  \
count            340.000000            340.000000                 340.000000   
mean               0.975867              0.531234                   0.034647   
std                0.032506              0.217532                   0.031502   
min                0.915575              0.078376                   0.002837   
25%                0.966230              0.346818                   0.009521   
50%                0.992980              0.579160                   0.023860   
75%                1.000000              0.700712                   0.047834   
max                1.000000              0.858160                   0.105303   

        Lobedness  Average Intensity   Average Contrast  Smoothness  \
count  340.000000         340.000000         340.000000  340.000000   
mean     0.284499           0.051209           0.124535    0.017491   
std      0.365318           0.035518           0.051860    0.013189   
min      0.001464           0.005022           0.033415    0.001115   
25%      0.016500           0.022843           0.083362    0.006901   
50%      0.103615           0.042087           0.119375    0.014050   
75%      0.416433           0.073046           0.163795    0.026127   
max      1.016331           0.148349           0.280810    0.054967   

        Third moment  Uniformity     Entropy  
count     340.000000  340.000000  340.000000  
mean        0.005678    0.000356    1.162630  
std         0.004495    0.000336    0.584854  
min         0.000229    0.000007    0.169400  
25%         0.002080    0.000102    0.718900  
50%         0.004447    0.000239    1.077450  
75%         0.008307    0.000516    1.554575  
max         0.017648    0.001137    2.708500

In [11]:
np.random.seed(7)
arr= np.array(np.random.rand(20)).reshape(10,2)

In [13]:
arr

array([[0.07630829, 0.77991879],
       [0.43840923, 0.72346518],
       [0.97798951, 0.53849587],
       [0.50112046, 0.07205113],
       [0.26843898, 0.4998825 ],
       [0.67923   , 0.80373904],
       [0.38094113, 0.06593635],
       [0.2881456 , 0.90959353],
       [0.21338535, 0.45212396],
       [0.93120602, 0.02489923]])

In [16]:
X = StandardScaler()

In [18]:
scaled_arr = X.fit_transform(arr)
scaled_arr

array([[-1.39522475,  0.93201877],
       [-0.1296922 ,  0.7523863 ],
       [ 1.75612561,  0.16382359],
       [ 0.08948178, -1.32037931],
       [-0.72373342,  0.04095785],
       [ 0.71196956,  1.00781355],
       [-0.33054158, -1.33983624],
       [-0.65485934,  1.34463703],
       [-0.91614429, -0.11100733],
       [ 1.59261863, -1.47041422]])

In [20]:
k_means = KMeans(n_clusters = 2)

In [22]:
k_means.fit(scaled_arr)

KMeans(n_clusters=2)

In [23]:
k_means.labels_

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 1])

In [25]:
silhouette_score(scaled_arr, k_means.labels_)

0.4069015400992441

In [27]:
scaled_df = X.fit_transform(df)
scaled_df

array([[ 0.03406572, -0.48209894, -0.97186457, ..., -0.0993394 ,
        -0.24107626,  0.02220937],
       [ 0.10516996, -0.42406912, -0.78138363, ..., -0.66180812,
        -0.83677884, -0.79802302],
       [ 0.22771539, -0.37133521, -0.6338121 , ..., -1.06006173,
        -0.94670245, -1.23143573],
       ...,
       [-1.76156859, -0.97935258,  1.37079505, ...,  2.32734448,
         0.28950626,  0.90903502],
       [-0.57678648, -0.85563074,  1.03207692, ...,  0.11405691,
        -0.27155102, -0.01717466],
       [-1.19182128, -0.91490004,  1.74264253, ...,  1.73998658,
        -0.0808678 ,  0.68437481]])

In [28]:
k_means = KMeans(n_clusters = 4)

In [29]:
k_means.fit(scaled_df)
labels = k_means.labels_

In [30]:
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       3, 1, 3, 1, 3, 3, 3, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 3, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 1, 3, 3, 1, 3,
       1, 3, 3, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 0, 1, 1, 3,
       3, 0, 3, 3, 1, 1, 1, 1, 3, 3, 1, 3, 1, 1, 3, 3, 1, 3, 3, 3, 3, 1,
       3, 1, 0, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 1, 3, 3, 2,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 3, 1, 1, 1,
       1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 1,
       1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
       3, 3, 1, 3, 3, 1, 1, 3, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 1,

In [31]:
k_means.inertia_

1895.2525135696264